stages:
  data:
    cmd: make data
    deps:
      - src/data/make_dataset.py
    outs:
      - data/raw

  featurize:
    cmd: make features
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/features/build_features.py

    params:
      - dataset.target
      - prepare.random_state
      - prepare.test_size

    outs:
      - data/processed
      - models/features.joblib

  train:
    cmd: make train
    deps:
      - data/processed/train.joblib
      - src/models/train_model.py
    params:
      - dataset.target
      - train.clf
      - train.clf_params
    outs:
      - models/model.joblib

  evaluate:
    cmd: make evaluation
    deps:
      - data/processed/test.joblib
      - src/models/evaluate_model.py
      - models/model.joblib
    params:
      - dataset.target
    metrics:
      - reports/scores.json:
          cache: false
    plots:
      - reports/prc.json:
          cache: false
          title: "Precision Recall"
          x_label: "Recall"
          y_label: "Precision"
          x: recall
          y: precision
      - reports/roc.json:
          cache: false
          title: "ROC"
          x_label: "False positive rate"
          y_label: "True positive rate"
          x: fpr
          y: tpr
      - reports/cfm.json:
          cache: false
          template: confusion
          x_label: "True label"
          y_label: "Predicted label"
          x: actual
          y: predicted
