dataset:
  target: Survived

prepare:
  random_state: 3141592
  split: 0.3
  stratify: y
  missing:
    categorical: ["Embarked"]
    numerical: ["Age"]

featurize:
  count: ["SibSp", "Parch"]
  boolean: ["SibSp", "Parch"]
  discretize: ["Fare"]
  title: ["Name"]

train:
  classifier: RandomForestClassifier
  classifier_args:
    random_state: 2077
    n_estimators: 1
    min_samples_split: 10
    n_jobs: -1
