dataset:
  target: Survived

prepare:
  random_state: 3141592
  test_size: 0.3

train:
  clf: RandomForestClassifier
  clf_params:
    random_state: 2077
    n_estimators: 10
    min_samples_split: 20
    n_jobs: -1
